# Country name to ISO code mapping for ratings data
COUNTRY_ISO_MAPPING = {
    'argentina': 'ARG',
    'armenia': 'ARM',
    'australia': 'AUS',
    'austria': 'AUT',
    'bangladesh': 'BGD',
    'belgium': 'BEL',
    'botswana': 'BWA',
    'brazil': 'BRA',
    'bulgaria': 'BGR',
    'canada': 'CAN',
    'chile': 'CHL',
    'china': 'CHN',
    'côte d\'ivoire': 'CIV',
    'colombia': 'COL',
    'croatia': 'HRV',
    'cyprus': 'CYP',
    'czech republic': 'CZE',
    'denmark': 'DNK',
    'egypt': 'EGY',
    'finland': 'FIN',
    'france': 'FRA',
    'germany': 'DEU',
    'greece': 'GRC',
    'hong kong': 'HKG',
    'hungary': 'HUN',
    'iceland': 'ISL',
    'india': 'IND',
    'indonesia': 'IDN',
    'ireland': 'IRL',
    'israel': 'ISR',
    'italy': 'ITA',
    'japan': 'JPN',
    'kenya': 'KEN',
    'south korea': 'KOR',
    'sri lanka': 'LKA',
    'latvia': 'LVA',
    'lithuania': 'LTU',
    'luxembourg': 'LUX',
    'malaysia': 'MYS',
    'malta': 'MLT',
    'mexico': 'MEX',
    'namibia': 'NAM',
    'netherlands': 'NLD',
    'nigeria': 'NGA',
    'norway': 'NOR',
    'new zealand': 'NZL',
    'pakistan': 'PAK',
    'peru': 'PER',
    'philippines': 'PHL',
    'poland': 'POL',
    'portugal': 'PRT',
    'qatar': 'QAT',
    'romania': 'ROU',
    'russia': 'RUS',
    'serbia': 'SRB',
    'singapore': 'SGP',
    'slovakia': 'SVK',
    'slovenia': 'SVN',
    'south africa': 'ZAF',
    'spain': 'ESP',
    'sweden': 'SWE',
    'switzerland': 'CHE',
    'taiwan': 'TWN',
    'thailand': 'THA',
    'turkey': 'TUR',
    'uganda': 'UGA',
    'united kingdom': 'GBR',
    'united states': 'USA',
    'vietnam': 'VNM',
    'zambia': 'ZMB'
}

def get_iso_code(country_name):
    """Convert country name to ISO code"""
    return COUNTRY_ISO_MAPPING.get(country_name.lower(), country_name.upper()) 